env: ${ENV}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${ENV} # set this to the right environment esp for docker => live

  mail: # https://myaccount.google.com/lesssecureapps?pli=1&rapt=AEjHL4N11isNtPUV0AmxD8ENeOcbgQEIGHimyned69xLBrAFHfAk5-iUXfYazUCckQFXbhtacVU8fIscVN24R6qx1SwxRUX71g
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # for swagger bug

domain:
  url: ${DOMAIN_URL}

server:
  port: ${PORT}

jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration_minutes: ${JWT_EXPIRATION_MINUTES}

remember_me:
  secret_key: nothing

initial_employee_coker_password:
  ${PASSWORD_DEFAULT_DELCOKER}

registration_confirmation_redirect_url: ${REGISTRATION_CONFIRMATION_REDIRECT_URL}

db:
  driver: ${DB_DRIVER_EBEAN}
  language: ${DB_LANGUAGE}
  server: ${DB_SERVER}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  executeddl: ${DB_EXECUTE_DDL} # overwrites/resets db if set to true CAUTION ⚠️
  seed: ${DB_SEED} # run migration script

cache:
  server: ${CACHE_SERVER}
  password: ${CACHE_PASSWORD}
  enabled: ${CACHE_ENABLED}
  replicas: ${CACHE_REPLICAS}

logging:
  file:
    path: opt/logs
    name: deloop-pos_${env}.log

default:
  hello:
    greeting: greeting from ${env}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs



